### ISSUE TITLE
bug: disable-landscabe-mode fails to patch

### ISSUE THREAD

**Issue by ABCPascal** [d4n3436/revanced-patches-android5#13]
### Type

Error while patching

### Bug description

Found the bug while trying to include the patch.

### Steps to reproduce

Step 1: Include disable-landscabe-mode on Android 13
Step 2: Patch

### Relevant log output

```shell
- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: motorola edge 30 ultra
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

- Patch Info
App: com.google.android.youtube v16.40.36
Patches version: v2.161.2
Patches: client-spoof, custom-branding-icon-afn-red, custom-branding-name, custom-video-speed, default-video-quality, default-video-speed, disable-haptic-feedback, disable-landscape-mode, disable-update-screen, enable-external-browser, enable-minimized-playback, enable-old-quality-layout, enable-open-links-directly, enable-seekbar-tapping, enable-tablet-miniplayer, enable-wide-searchbar, force-premium-heading, force-vp9-codec, header-switch, hide-auto-captions, hide-auto-player-popup-panels, hide-autoplay-button, hide-cast-button, hide-channel-watermark, hide-comment-component, hide-create-button, hide-crowdfunding-box, hide-email-address, hide-endscreen-cards, hide-endscreen-overlay, hide-firsttime-background-notification, hide-fullscreen-panels, hide-general-ads, hide-info-cards, hide-live-chat-button, hide-mix-playlists, hide-next-prev-button, hide-player-captions-button, hide-player-overlay-filter, hide-shorts-button, hide-shorts-component, hide-snackbar, hide-suggested-actions, hide-time-and-seekbar, hide-tooltip-content, hide-video-ads, layout-switch, materialyou, microg-support, optimize-resource, os-version-check, overlay-buttons, patch-options [Application Name of YouTube: ReVanced Extended, Package Name of YouTube: app.rvx.android.youtube, Custom Speed Values: 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 3.0, 5.0, Overlay button icon selection: new, Background color for the dark theme: @android:color/black], return-youtube-dislike, sponsorblock, spoof-app-version, spoof-player-parameters, swipe-controls, switch-create-notification, theme, translations

- Settings
Allow changing patch selection: true
Version compatibility check: true
Show universal patches: false
Patches source: d4n3436/revanced-patches-android5
Integration source: d4n3436/revanced-integrations

- Logs
Copying APK
Reading APK
Decoding app manifest
Loading patches
Merging integrations
Deleting existing resource cache directory
Decoding resources
Executing patches
client-spoof succeeded
custom-branding-icon-afn-red succeeded
custom-branding-name succeeded
custom-video-speed succeeded
default-video-quality succeeded
default-video-speed succeeded
disable-haptic-feedback succeeded
disable-landscape-mode failed: app.revanced.patcher.patch.PatchException: 'disable-landscape-mode' depends on 'LandScapeModeBytecodePatch' that raised an exception: app.revanced.patcher.patch.PatchException: Failed to resolve OrientationParentFingerprint
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend$executePatch(Unknown Source:130)
	at app.revanced.patcher.Patcher$apply$1.invokeSuspend(Unknown Source:267)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at app.revanced.patcher.Patcher$apply$1.invoke(SourceFile:0)
	at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
	at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:71)
	at app.revanced.manager.flutter.MainActivity$runPatcher$1$2$1.invokeSuspend(Unknown Source:54)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:11)
	at kotlinx.coroutines.DispatchedTask.run(Unknown Source:93)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(Unknown Source:46)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Unknown Source:23)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Unknown Source:73)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:0)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Unknown Source:6)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:0)
	at app.revanced.manager.flutter.MainActivity.runPatcher$lambda$33(Unknown Source:671)
	at app.revanced.manager.flutter.MainActivity.$r8$lambda$S_uZlejwCCJ2DlEIsq6PpeMbHBY(SourceFile:0)
	at app.revanced.manager.flutter.MainActivity$$ExternalSyntheticLambda2.run(SourceFile:0)
	at java.lang.Thread.run(Thread.java:1012)
disable-update-screen succeeded
enable-external-browser succeeded
enable-minimized-playback succeeded
enable-old-quality-layout succeeded
enable-open-links-directly succeeded
enable-seekbar-tapping succeeded
enable-tablet-miniplayer succeeded
enable-wide-searchbar succeeded
force-premium-heading succeeded
force-vp9-codec succeeded
header-switch succeeded
hide-auto-captions succeeded
hide-auto-player-popup-panels succeeded
hide-autoplay-button succeeded
hide-cast-button succeeded
hide-channel-watermark succeeded
hide-comment-component succeeded
hide-create-button succeeded
hide-crowdfunding-box succeeded
hide-email-address succeeded
hide-endscreen-cards succeeded
hide-endscreen-overlay succeeded
hide-firsttime-background-notification succeeded
hide-fullscreen-panels succeeded
hide-general-ads succeeded
hide-info-cards succeeded
hide-live-chat-button succeeded
hide-mix-playlists succeeded
hide-next-prev-button succeeded
hide-player-captions-button succeeded
hide-player-overlay-filter succeeded
hide-shorts-button succeeded
hide-shorts-component succeeded
hide-snackbar succeeded
hide-suggested-actions succeeded
hide-time-and-seekbar succeeded
hide-tooltip-content succeeded
hide-video-ads succeeded
layout-switch succeeded
materialyou succeeded
microg-support succeeded
optimize-resource succeeded
os-version-check succeeded
overlay-buttons succeeded
patch-options succeeded
return-youtube-dislike succeeded
sponsorblock succeeded
spoof-app-version succeeded
spoof-player-parameters succeeded
swipe-controls succeeded
switch-create-notification succeeded
theme succeeded
translations succeeded
Compiling modified dex files
Compiling modified resources
Signing APK
Patched
```

### Device Environment

- Device Info
ReVanced Manager: 1.17.1
Build: release
Model: motorola edge 30 ultra
Android version: 13
Supported architectures: arm64-v8a, armeabi-v7a, armeabi
Root permissions: No

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by d4n3436** [comment]
The `disable-landscape-mode` patch is excluded by default so I don't consider it a supported patch. I might fix it if the issue is simple enough.
