### ISSUE TITLE
bug: java.io.IOException

### ISSUE THREAD

**Issue by Sofie99** [d4n3436/revanced-patches-android5#2]
### Type

Error while patching

### Bug description

error when  Signing YouTube_ReVanced_16.40.36_aligned.apk to YouTube_ReVanced_16.40.36_signed.apk

### Steps to reproduce

follow step in README

### Relevant log output

```shell
Microsoft Windows [Version 10.0.22621.1555]
(c) Microsoft Corporation. All rights reserved.

C:\Users\Hexated-PC\Downloads\Youtube>java -jar revanced-cli.jar -a YouTube_16.40.36.apk -o YouTube_ReVanced_16.40.36.apk -b revanced-patches-2.160.5.jar -m revanced-integrations-0.96.4.apk -i microg-support -i protobuf-spoof -i client-spoof -i hide-video-ads --exclusive
INFO: Reading dex files
INFO: Decoding AndroidManifest.xml only, because resources are not needed
INFO: Skipping custom-branding-icon-afn-blue: Excluded by default
INFO: Skipping custom-branding-icon-afn-red: Excluded by default
INFO: Skipping custom-branding-icon-revancify: Excluded by default
INFO: Skipping custom-branding-name: Excluded by default
INFO: Skipping custom-seekbar-color: Excluded by default
INFO: Skipping custom-video-speed: Excluded by default
INFO: Skipping default-video-quality: Excluded by default
INFO: Skipping default-video-speed: Excluded by default
INFO: Skipping disable-haptic-feedback: Excluded by default
INFO: Skipping enable-external-browser: Excluded by default
INFO: Skipping enable-minimized-playback: Excluded by default
INFO: Skipping enable-new-layout: Excluded by default
INFO: Skipping enable-old-quality-layout: Excluded by default
INFO: Skipping enable-open-links-directly: Excluded by default
INFO: Skipping enable-seekbar-tapping: Excluded by default
INFO: Skipping enable-tablet-miniplayer: Excluded by default
INFO: Skipping enable-wide-searchbar: Excluded by default
INFO: Skipping force-enable-new-layout: Excluded by default
INFO: Skipping force-premium-heading: Excluded by default
INFO: Skipping force-vp9-codec: Excluded by default
INFO: Skipping header-switch: Excluded by default
INFO: Skipping hide-auto-captions: Excluded by default
INFO: Skipping hide-auto-player-popup-panels: Excluded by default
INFO: Skipping hide-autoplay-button: Excluded by default
INFO: Skipping hide-button-container: Excluded by default
INFO: Skipping hide-cast-button: Excluded by default
INFO: Skipping hide-channel-watermark: Excluded by default
INFO: Skipping hide-comment-component: Excluded by default
INFO: Skipping hide-create-button: Excluded by default
INFO: Skipping hide-crowdfunding-box: Excluded by default
INFO: Skipping hide-email-address: Excluded by default
INFO: Skipping hide-endscreen-cards: Excluded by default
INFO: Skipping hide-endscreen-overlay: Excluded by default
INFO: Skipping hide-filmstrip-overlay: Excluded by default
INFO: Skipping hide-firsttime-background-notification: Excluded by default
INFO: Skipping hide-flyout-panel: Excluded by default
INFO: Skipping hide-fullscreen-panels: Excluded by default
INFO: Skipping hide-general-ads: Excluded by default
INFO: Skipping hide-info-cards: Excluded by default
INFO: Skipping hide-live-chat-button: Excluded by default
INFO: Skipping hide-mix-playlists: Excluded by default
INFO: Skipping hide-next-prev-button: Excluded by default
INFO: Skipping hide-player-captions-button: Excluded by default
INFO: Skipping hide-player-overlay-filter: Excluded by default
INFO: Skipping hide-shorts-button: Excluded by default
INFO: Skipping hide-shorts-component: Excluded by default
INFO: Skipping hide-shorts-pivot-bar: Excluded by default
INFO: Skipping hide-snackbar: Excluded by default
INFO: Skipping hide-startup-shorts-player: Excluded by default
INFO: Skipping hide-stories: Excluded by default
INFO: Skipping hide-suggested-actions: Excluded by default
INFO: Skipping hide-time-and-seekbar: Excluded by default
INFO: Skipping hide-tooltip-content: Excluded by default
INFO: Skipping layout-switch: Excluded by default
INFO: Skipping materialyou: Excluded by default
INFO: Skipping optimize-resource: Excluded by default
INFO: Skipping overlay-buttons: Excluded by default
INFO: Skipping patch-options: Excluded by default
INFO: Skipping remove-player-button-background: Excluded by default
INFO: Skipping return-youtube-dislike: Excluded by default
INFO: Skipping settings: Excluded by default
INFO: Skipping sponsorblock: Excluded by default
INFO: Skipping swipe-controls: Excluded by default
INFO: Skipping switch-create-notification: Excluded by default
INFO: Skipping theme: Excluded by default
INFO: Skipping translations: Excluded by default
INFO: Merging revanced-integrations-0.96.4.apk
INFO: Deleting existing resource cache directory
SEVERE: Failed to delete existing resource cache directory
INFO: Decoding resources
INFO: client-spoof succeeded
INFO: hide-video-ads succeeded
INFO: microg-support succeeded
INFO: protobuf-spoof succeeded
INFO: Compiling resources
INFO: Writing modified dex files
INFO: Aligning YouTube_16.40.36.apk to YouTube_ReVanced_16.40.36_aligned.apk
INFO: Signing YouTube_ReVanced_16.40.36_aligned.apk to YouTube_ReVanced_16.40.36_signed.apk
org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$BCKeyStoreException: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(Unknown Source)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1167)
        at app.revanced.utils.signing.Signer.newKeystore(Signer.kt:29)
        at app.revanced.utils.signing.Signer.signApk(Signer.kt:58)
        at app.revanced.cli.signing.Signing.sign(Signing.kt:10)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:177)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.io.IOException: Error initialising store of key store: java.lang.SecurityException: JCE cannot authenticate the provider BC
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.makePBECipher(Unknown Source)
        at org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi$StoreEntry.<init>(Unknown Source)
        ... 15 more
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Sofie99** [comment]
btw i use java jdk-17

🙏  🙏  🙏  🙏  🙏

**Comment by d4n3436** [comment]
You need Zulu OpenJDK 17, it's mentioned on the [prerequisites page](https://github.com/revanced/revanced-cli/blob/main/docs/0_prerequisites.md) of revanced-cli.

**Comment by Sofie99** [comment]
> You need Zulu OpenJDK 17, it's mentioned on the [prerequisites page](https://github.com/revanced/revanced-cli/blob/main/docs/0_prerequisites.md) of revanced-cli.

thx it working 😄
