### ISSUE TITLE
bug: crashes when pressing the gear icon in video player with spoof version on

### ISSUE THREAD

**Issue by jpa102** [d4n3436/revanced-patches-android5#23]
### Type

Error at runtime

### Bug description

yt revanced crashes whenever i press the gear icon inside the video player (e.g: adjusting video quality) or is it just me?
this occurs when i spoof **above** the base version **16.40.36** which is already gone and gives out **error 400** (this does not happen when i used to spoof **below** the *original version,* currently using **17.33.42** version to spoof)

### Steps to reproduce

1. spoof to 17.33.42 or higher
2. go to any video
3. press gear icon

### Relevant log output

```shell
m12:/ $ logcat | grep AndroidRuntime
04-01 15:13:58.725 15713 15733 E AndroidRuntime: FATAL EXCEPTION: McsHandler
04-01 15:13:58.725 15713 15733 E AndroidRuntime: Process: com.mgoogle.android.gms:persistent, PID: 15713
04-01 15:13:58.725 15713 15733 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.NetworkInfo.getTypeName()' on a null object reference
04-01 15:13:58.725 15713 15733 E AndroidRuntime:        at org.microg.gms.gcm.McsService.connect(Unknown Source:46)
04-01 15:13:58.725 15713 15733 E AndroidRuntime:        at org.microg.gms.gcm.McsService.handleMessage(Unknown Source:279)
04-01 15:13:58.725 15713 15733 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-01 15:13:58.725 15713 15733 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
04-01 15:13:58.725 15713 15733 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
04-01 15:13:58.725 15713 15733 E AndroidRuntime:        at org.microg.gms.gcm.McsService$HandlerThread.run(Unknown Source:85)
04-01 15:14:05.417 16036 16052 E AndroidRuntime: FATAL EXCEPTION: McsHandler
04-01 15:14:05.417 16036 16052 E AndroidRuntime: Process: com.mgoogle.android.gms:persistent, PID: 16036
04-01 15:14:05.417 16036 16052 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.NetworkInfo.getTypeName()' on a null object reference
04-01 15:14:05.417 16036 16052 E AndroidRuntime:        at org.microg.gms.gcm.McsService.connect(Unknown Source:46)
04-01 15:14:05.417 16036 16052 E AndroidRuntime:        at org.microg.gms.gcm.McsService.handleMessage(Unknown Source:279)
04-01 15:14:05.417 16036 16052 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-01 15:14:05.417 16036 16052 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
04-01 15:14:05.417 16036 16052 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
04-01 15:14:05.417 16036 16052 E AndroidRuntime:        at org.microg.gms.gcm.McsService$HandlerThread.run(Unknown Source:85)
04-01 15:14:06.876 16132 16177 E AndroidRuntime: FATAL EXCEPTION: McsHandler
04-01 15:14:06.876 16132 16177 E AndroidRuntime: Process: com.mgoogle.android.gms:persistent, PID: 16132
04-01 15:14:06.876 16132 16177 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.NetworkInfo.getTypeName()' on a null object reference
04-01 15:14:06.876 16132 16177 E AndroidRuntime:        at org.microg.gms.gcm.McsService.connect(Unknown Source:46)
04-01 15:14:06.876 16132 16177 E AndroidRuntime:        at org.microg.gms.gcm.McsService.handleMessage(Unknown Source:279)
04-01 15:14:06.876 16132 16177 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
04-01 15:14:06.876 16132 16177 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
04-01 15:14:06.876 16132 16177 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
04-01 15:14:06.876 16132 16177 E AndroidRuntime:        at org.microg.gms.gcm.McsService$HandlerThread.run(Unknown Source:85)

04-01 19:32:28.278  5269  5269 D AndroidRuntime: Shutting down VM
04-01 19:32:28.282  5269  5269 E AndroidRuntime: FATAL EXCEPTION: main
04-01 19:32:28.282  5269  5269 E AndroidRuntime: Process: app.rvx.android.youtube, PID: 5269
04-01 19:32:28.282  5269  5269 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at nwl.aH(PG:8)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at akfb.mj(PG:5)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at cd.lO(PG:3)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at bv.lO(PG:1)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at di.c(PG:16)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at di.e(PG:201)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at dc.at(PG:112)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at dc.av(PG:11)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at dc.G(PG:3)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at bf.d(PG:2)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at bv.qq(PG:4)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at com.google.android.apps.youtube.app.watch.bottomsheet.PlayerOverflowBottomSheetController.h(PG:9)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at com.google.android.apps.youtube.app.watch.bottomsheet.PlayerOverflowBottomSheetController.g(PG:1)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at kwl.onClick(PG:2)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at android.view.View.performClick(View.java:7892)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7869)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:30891)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8762)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
04-01 19:32:28.282  5269  5269 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
04-01 19:38:02.005 16647 16647 D AndroidRuntime: Shutting down VM
04-01 19:38:02.023 16647 16647 E AndroidRuntime: FATAL EXCEPTION: main
04-01 19:38:02.023 16647 16647 E AndroidRuntime: Process: app.rvx.android.youtube, PID: 16647
04-01 19:38:02.023 16647 16647 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at nwl.aH(PG:8)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at akfb.mj(PG:5)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at cd.lO(PG:3)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at bv.lO(PG:1)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at di.c(PG:16)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at di.e(PG:201)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at dc.at(PG:112)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at dc.av(PG:11)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at dc.G(PG:3)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at bf.d(PG:2)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at bv.qq(PG:4)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at com.google.android.apps.youtube.app.watch.bottomsheet.PlayerOverflowBottomSheetController.h(PG:9)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at com.google.android.apps.youtube.app.watch.bottomsheet.PlayerOverflowBottomSheetController.g(PG:1)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at kwl.onClick(PG:2)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at android.view.View.performClick(View.java:7892)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7869)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:30891)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:942)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8762)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
04-01 19:38:02.023 16647 16647 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Additional context

the log mentions com.mgoogle.android.gms, which is the vanced microg that i have installed before patching to latest version, so bugs *"may"* be different

the base 16.40.36 isn't just built to handle layouts from 17.33.42 and above, so maybe that causes the issue
other issues include when spoofing:

- unclickable videos when signed in
- recently watched videos preview don't render in library
- community posts can't be liked in home page (and possibly in watch page action buttons when installed in android 13) (probably requires the new like icon animation)
- dislike counter doesn't appear and look just like in official revanced
- explore button doesn't appear in the snackbar
- partially broken shorts player

### Device Environment

android 5, oppo a37fw (main)
android 13, samsung m12 (secondary)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by d4n3436** [comment]
This is a known issue that occurs when spoofing to version 17.06.34+

> dislike counter doesn't appear and look just like in official revanced

This definitely works

**Comment by Nehalemna** [comment]
Same issue and it stops after playing for 1min

**Comment by guranu** [comment]
> This a known issue that occurs when spoofing to version 17.06.34+
> 
> > dislike counter doesn't appear and look just like in official revanced
> 
> This definitely works

It dosen't show the number of dislikes (i.e return youtube dislike dosen't work).

**Comment by jpa102** [comment]
oh okay, it now shows in the latest patch. like i said, i made this issue before patching to latest version so it may be different now

now the only problem that i see is that the dislike counts disappear after pressing the like button (like it completely disappears without showing back up unlike in kitadai's version), i would attach videos but it's a pain for me to record and attach them here without resorting to 3rd party file hosts and trying to meet the 10mb file size mark. but i'll try doing that later
