### ISSUE TITLE
feat(patch): Background playback support

### ISSUE THREAD

**Issue by i1itione** [d4n3436/revanced-patches-android5#3]
### Application

YouTube v16.40.36

### Issue

It doesn't support background playback currently.

enable-minimized-playback failed:
app.revanced.patcher.patch.PatchResultError: 'enable-minimized-playback' depends on 'enable-minimized-playback-bytecode-patch' but the following error was raised: Failed to resolve MinimizedPlaybackSettingsFingerprint
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:304)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)

### Patch

To support background playback

### Motivation

It is used for turning off screen when just to listening to the sound of youtube videos.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by d4n3436** [comment]
I will push a fix only because it's easy to solve. I probably won't fix more patches.
