### ISSUE TITLE
bug: build failed with revanced-integrations-0.96.5 / revanced-patches-2.160.7

### ISSUE THREAD

**Issue by i1itione** [d4n3436/revanced-patches-android5#5]
### Type

Error while patching

### Bug description

I use revanced-cli-2.21.1-all.jar with revanced-integrations-0.96.5.apk / revanced-patches-2.160.7.jar but it don't work.

### Steps to reproduce

java -jar revanced-cli-2.21.1-all.jar -a YouTube_16.40.36.apk -o YouTube_ReVanced_16.40.36.apk -b revanced-patches-2.160.7.jar -m revanced-integrations-0.96.5.apk -i microg-support -i spoof-player-parameters -i client-spoof -i hide-video-ads -i enable-minimized-playback --exclusive

### Relevant log output

```shell
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:311)
        at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:301)
        at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:36)
        at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:350)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
        at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
        at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
        at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.main.MainKt.main(Main.kt:7)
Caused by: java.lang.NoSuchMethodError: 'void app.revanced.patcher.fingerprint.method.impl.MethodFingerprint.<init>(java.lang.String, java.lang.Integer, java.lang.Iterable, java.lang.Iterable, java.lang.Iterable, kotlin.jvm.functions.Function2, int, kotlin.jvm.internal.DefaultConstructorMarker)'
        at app.revanced.patches.youtube.misc.clientspoof.bytecode.fingerprints.UserAgentHeaderBuilderFingerprint.<init>(UserAgentHeaderBuilderFingerprint.kt:6)
        at app.revanced.patches.youtube.misc.clientspoof.bytecode.fingerprints.UserAgentHeaderBuilderFingerprint.<clinit>(UserAgentHeaderBuilderFingerprint.kt)
        at app.revanced.patches.youtube.misc.clientspoof.bytecode.patch.ClientSpoofBytecodePatch.<init>(ClientSpoofBytecodePatch.kt:19)
        ... 23 more
```

### Device Environment

Windows 10 x64 / zulu17.44.15-ca-jre17.0.8-win_x64

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by eldepor** [comment]
Try with [revanced-cli-2.22.0-all.jar](https://github.com/revanced/revanced-cli/releases/tag/v2.22.0)

**Comment by i1itione** [comment]
> Try with [revanced-cli-2.22.0-all.jar](https://github.com/revanced/revanced-cli/releases/tag/v2.22.0)

It works!! Thanks a lot.
