### ISSUE TITLE
Got this instead with the other cli

### ISSUE THREAD

**Issue by Aman0605** [d4n3436/revanced-patches-android5#8]
Got this instead

~/downloads $ java -jar revanced-cli.jar patch YouTube_16.40.36.apk -p -o YouTube_ReVanced_16.40.36.apk -b revanced-patches-2.160.9.jar -m revanced-integrations-0.96.6.apk -i microg-support -i spoof-player-parameters -i client-spoof -i hide-video-ads -i enable-minimized-playback -i disable-update-screen --exclusive
INFO: Loading patches
INFO: Setting patch options
INFO: Decoding app manifest
INFO: custom-branding-icon-afn-blue excluded by default
INFO: custom-branding-icon-afn-red excluded by default
INFO: custom-branding-icon-revancify excluded by default
INFO: custom-branding-name excluded by default
INFO: custom-seekbar-color excluded by default
INFO: custom-video-speed excluded by default
INFO: default-video-quality excluded by default
INFO: default-video-speed excluded by default
INFO: disable-haptic-feedback excluded by default
INFO: disable-landscape-mode excluded by default
INFO: enable-external-browser excluded by default
INFO: enable-old-quality-layout excluded by default
INFO: enable-open-links-directly excluded by default
INFO: enable-seekbar-tapping excluded by default
INFO: enable-tablet-miniplayer excluded by default
INFO: enable-wide-searchbar excluded by default
INFO: force-premium-heading excluded by default
INFO: force-vp9-codec excluded by default
INFO: header-switch excluded by default
INFO: hide-auto-captions excluded by default
INFO: hide-auto-player-popup-panels excluded by default
INFO: hide-autoplay-button excluded by default
INFO: hide-button-container excluded by default
INFO: hide-cast-button excluded by default
INFO: hide-channel-watermark excluded by default
INFO: hide-comment-component excluded by default
INFO: hide-create-button excluded by default
INFO: hide-crowdfunding-box excluded by default
INFO: hide-email-address excluded by default
INFO: hide-endscreen-cards excluded by default
INFO: hide-endscreen-overlay excluded by default
INFO: hide-filmstrip-overlay excluded by default
INFO: hide-firsttime-background-notification excluded by default
INFO: hide-flyout-panel excluded by default
INFO: hide-fullscreen-panels excluded by default
INFO: hide-general-ads excluded by default
INFO: hide-info-cards excluded by default
INFO: hide-live-chat-button excluded by default
INFO: hide-mix-playlists excluded by default
INFO: hide-next-prev-button excluded by default
INFO: hide-player-captions-button excluded by default
INFO: hide-player-overlay-filter excluded by default
INFO: hide-shorts-button excluded by default
INFO: hide-shorts-component excluded by default
INFO: hide-snackbar excluded by default
INFO: hide-startup-shorts-player excluded by default
INFO: hide-stories excluded by default
INFO: hide-suggested-actions excluded by default
INFO: hide-time-and-seekbar excluded by default
INFO: hide-tooltip-content excluded by default
INFO: layout-switch excluded by default
INFO: materialyou excluded by default
INFO: optimize-resource excluded by default
INFO: os-version-check excluded by default
INFO: overlay-buttons excluded by default
INFO: patch-options excluded by default
INFO: remove-player-button-background excluded by default
INFO: return-youtube-dislike excluded by default
INFO: settings excluded by default
INFO: sponsorblock excluded by default
INFO: spoof-app-version excluded by default
INFO: swipe-controls excluded by default
INFO: switch-create-notification excluded by default
INFO: theme excluded by default
INFO: translations excluded by default
INFO: Merging integrations
INFO: Deleting existing resource cache directory
INFO: Decoding resources
INFO: Executing patches
INFO: client-spoof succeeded
INFO: disable-update-screen succeeded
INFO: enable-minimized-playback succeeded
INFO: hide-video-ads succeeded
INFO: microg-support succeeded
INFO: spoof-player-parameters succeeded
INFO: Compiling modified dex files
INFO: Compiling modified resources
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec: [/data/data/com.termux/files/usr/tmp/brut_util_Jar_31224131386762619211333693802385712068.tmp, compile, --dir, /data/data/com.termux/files/home/downloads/revanced-resource-cache/res, --legacy, -o, /data/data/com.termux/files/home/downloads/revanced-resource-cache/build/resources.zip]
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
        at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:391)
        at app.revanced.patcher.data.ResourceContext.get(ResourceContext.kt:126)
        at app.revanced.patcher.Patcher.get(Patcher.kt:232)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:195)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)
Caused by: brut.common.BrutException: could not exec: [/data/data/com.termux/files/usr/tmp/brut_util_Jar_31224131386762619211333693802385712068.tmp, compile, --dir, /data/data/com.termux/files/home/downloads/revanced-resource-cache/res, --legacy, -o, /data/data/com.termux/files/home/downloads/revanced-resource-cache/build/resources.zip]
        at brut.util.OS.exec(OS.java:107)
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
        ... 13 more
Caused by: java.io.IOException: Cannot run program "/data/data/com.termux/files/usr/tmp/brut_util_Jar_31224131386762619211333693802385712068.tmp": error=14, Bad address
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
        at brut.util.OS.exec(OS.java:97)
        ... 14 more
Caused by: java.io.IOException: error=14, Bad address
        at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)8
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
        ... 16 more
~/downloads $

_Originally posted by @Aman0605 in https://github.com/d4n3436/revanced-patches-android5/issues/7#issuecomment-1774051356_

**Comment by d4n3436** [comment]
I haven't tested the CLI on Termux so it's probably not supported.
