### ISSUE TITLE
options.json missing?

### ISSUE THREAD

**Issue by chloelemaire** [d4n3436/revanced-patches-android5#9]
i execute with "Patch with the following command (file names changed for brevity):"

but it seems that the option.json file doesn't exist and I get an error.

I think options.json is the file where revanced picks what to patch, but I don't know anything about it. Any suggestions?

C:\Program Files\OpenLogic\jdk-17.0.9.9-hotspot\bin>java.exe -jar b:\revanced-cli.jar patch b:\YouTube.apk -p -o b:\YouTube_ReVanced_16.40.36.apk -b b:\revanced-patches-2.161.0.jar -m b:\revanced-integrations-0.96.7.apk
?뺣낫: Loading patches

?뺣낫: Setting patch options

java.io.FileNotFoundException: options.json (액세스가 거부되었습니다) <- ※means access denied
        at java.base/java.io.FileOutputStream.open0(Native Method)
        at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
        at kotlin.io.FilesKt__FileReadWriteKt.writeBytes(FileReadWrite.kt:108)
        at kotlin.io.FilesKt__FileReadWriteKt.writeText(FileReadWrite.kt:134)
        at kotlin.io.FilesKt__FileReadWriteKt.writeText$default(FileReadWrite.kt:134)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:164)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:40)

**Comment by chloelemaire** [comment]
sry i missed execute cmd to admin
